// frontend/src/lib/components/TradeMobileCard.svelte
<script lang="ts">
	import { createEventDispatcher } from 'svelte';
	import { TrendingUp, TrendingDown, Calendar, Hash, Edit, Trash2 } from 'lucide-svelte';
	import type { Trade } from '$lib/stores/trades';
	
	export let trade: Trade;
	export let isSelected = false;
	
	const dispatch = createEventDispatcher();
	
	function handleEdit() {
		dispatch('edit', { trade });
	}
	
	function handleDelete() {
		dispatch('delete', { id: trade.id });
	}
	
	function handleToggleSelect() {
		dispatch('toggleSelect', { id: trade.id });
	}
	
	function formatDate(dateStr: string): string {
		const date = new Date(dateStr);
		return date.toLocaleDateString('en-US', {
			month: 'short',
			day: 'numeric',
			year: 'numeric'
		});
	}
	
	function formatTime(dateStr: string): string {
		const date = new Date(dateStr);
		return date.toLocaleTimeString('en-US', {
			hour: '2-digit',
			minute: '2-digit'
		});
	}
	
	function formatCurrency(value: number): string {
		return new Intl.NumberFormat('en-US', {
			style: 'currency',
			currency: 'USD'
		}).format(value);
	}
</script>

<div class="trade-card" class:selected={isSelected}>
	<div class="trade-header">
		<div class="symbol-section">
			<h3>{trade.symbol}</h3>
			<span class="side" class:long={trade.side === 'long'} class:short={trade.side === 'short'}>
				{#if trade.side === 'long'}
					<TrendingUp size={14} />
				{:else}
					<TrendingDown size={14} />
				{/if}
				{trade.side.toUpperCase()}
			</span>
		</div>
		<div class="pnl" class:positive={trade.pnl > 0} class:negative={trade.pnl < 0}>
			{formatCurrency(trade.pnl)}
		</div>
	</div>
	
	<div class="trade-details">
		<div class="detail-row">
			<div class="detail">
				<span class="label">Entry</span>
				<span class="value">{formatCurrency(trade.entryPrice)}</span>
			</div>
			<div class="detail">
				<span class="label">Exit</span>
				<span class="value">{formatCurrency(trade.exitPrice || 0)}</span>
			</div>
			<div class="detail">
				<span class="label">Qty</span>
				<span class="value">{trade.quantity}</span>
			</div>
		</div>
		
		<div class="date-row">
			<Calendar size={14} />
			<span>{formatDate(trade.entryDate)}</span>
			<span class="time">{formatTime(trade.entryDate)}</span>
		</div>
		
		{#if trade.strategy}
			<div class="strategy-row">
				<Hash size={14} />
				<span>{trade.strategy}</span>
			</div>
		{/if}
	</div>
	
	<div class="trade-actions">
		<label class="checkbox-container">
			<input 
				type="checkbox" 
				checked={isSelected}
				on:change={handleToggleSelect}
			/>
			<span class="checkbox-label">Select</span>
		</label>
		<div class="action-buttons">
			<button on:click={handleEdit} class="action-button edit">
				<Edit size={16} />
			</button>
			<button on:click={handleDelete} class="action-button delete">
				<Trash2 size={16} />
			</button>
		</div>
	</div>
</div>

<style>
	.trade-card {
		background: white;
		border-radius: 12px;
		padding: 1rem;
		border: 2px solid #e0e0e0;
		transition: all 0.2s;
		margin-bottom: 0.75rem;
	}
	
	.trade-card.selected {
		border-color: #10b981;
		background: #f0fdf4;
	}
	
	.trade-header {
		display: flex;
		justify-content: space-between;
		align-items: flex-start;
		margin-bottom: 0.75rem;
	}
	
	.symbol-section {
		display: flex;
		align-items: center;
		gap: 0.75rem;
	}
	
	.symbol-section h3 {
		font-size: 1.25rem;
		margin: 0;
		font-weight: 600;
	}
	
	.side {
		display: flex;
		align-items: center;
		gap: 0.25rem;
		padding: 0.25rem 0.75rem;
		border-radius: 20px;
		font-size: 0.75rem;
		font-weight: 500;
	}
	
	.side.long {
		background: #d1fae5;
		color: #065f46;
	}
	
	.side.short {
		background: #fee2e2;
		color: #991b1b;
	}
	
	.pnl {
		font-size: 1.25rem;
		font-weight: 600;
	}
	
	.pnl.positive {
		color: #10b981;
	}
	
	.pnl.negative {
		color: #ef4444;
	}
	
	.trade-details {
		display: flex;
		flex-direction: column;
		gap: 0.75rem;
		margin-bottom: 1rem;
	}
	
	.detail-row {
		display: flex;
		gap: 1.5rem;
	}
	
	.detail {
		display: flex;
		flex-direction: column;
		gap: 0.125rem;
	}
	
	.label {
		font-size: 0.75rem;
		color: #666;
	}
	
	.value {
		font-weight: 500;
		color: #333;
	}
	
	.date-row,
	.strategy-row {
		display: flex;
		align-items: center;
		gap: 0.5rem;
		font-size: 0.875rem;
		color: #666;
	}
	
	.time {
		color: #999;
	}
	
	.trade-actions {
		display: flex;
		justify-content: space-between;
		align-items: center;
		padding-top: 0.75rem;
		border-top: 1px solid #e0e0e0;
	}
	
	.checkbox-container {
		display: flex;
		align-items: center;
		gap: 0.5rem;
		cursor: pointer;
	}
	
	.checkbox-label {
		font-size: 0.875rem;
		color: #666;
	}
	
	.action-buttons {
		display: flex;
		gap: 0.5rem;
	}
	
	.action-button {
		padding: 0.5rem;
		background: white;
		border: 1px solid #e0e0e0;
		border-radius: 6px;
		color: #666;
		cursor: pointer;
		transition: all 0.2s;
		display: flex;
		align-items: center;
		justify-content: center;
	}
	
	.action-button:active {
		transform: scale(0.95);
	}
	
	.action-button.edit:hover {
		background: #e0f2fe;
		border-color: #7dd3fc;
		color: #0369a1;
	}
	
	.action-button.delete:hover {
		background: #fee2e2;
		border-color: #fca5a5;
		color: #dc2626;
	}
</style>

// frontend/src/components/TradeMobileCard.tsx
import React from 'react';
import { 
  TrendingUp, 
  TrendingDown, 
  Clock, 
  CheckCircle, 
  XCircle,
  MoreVertical
} from 'lucide-react';

interface Trade {
  id: number;
  symbol: string;
  direction: 'long' | 'short';
  pnl: number;
  pnl_percentage: number;
  entry_price: number;
  exit_price?: number;
  quantity: number;
  status: 'open' | 'closed';
  open_date: string;
  close_date?: string;
  duration?: number;
}

interface TradeMobileCardProps {
  trade: Trade;
  isSelected: boolean;
  onSelect: () => void;
  onQuickAction?: (action: string) => void;
}

const TradeMobileCard: React.FC<TradeMobileCardProps> = ({
  trade,
  isSelected,
  onSelect
}) => {
  const formatCurrency = (amount: number) => {
    const formatted = new Intl.NumberFormat('en-US', {
      style: 'currency',
      currency: 'USD',
      minimumFractionDigits: 2,
      maximumFractionDigits: 2
    }).format(Math.abs(amount));
    return amount >= 0 ? `+${formatted}` : `-${formatted}`;
  };

  const formatPercentage = (percentage: number) => {
    const formatted = Math.abs(percentage).toFixed(2);
    return percentage >= 0 ? `+${formatted}%` : `-${formatted}%`;
  };

  const formatDate = (dateString: string) => {
    const date = new Date(dateString);
    const now = new Date();
    const diffMs = now.getTime() - date.getTime();
    const diffHours = Math.floor(diffMs / (1000 * 60 * 60));
    
    if (diffHours < 1) {
      const diffMinutes = Math.floor(diffMs / (1000 * 60));
      return `${diffMinutes}m ago`;
    } else if (diffHours < 24) {
      return `${diffHours}h ago`;
    } else if (diffHours < 48) {
      return 'Yesterday';
    } else {
      return date.toLocaleDateString('en-US', { month: 'short', day: 'numeric' });
    }
  };

  const formatDuration = (hours?: number) => {
    if (!hours) return '-';
    if (hours < 1) return `${Math.round(hours * 60)}m`;
    if (hours < 24) return `${hours.toFixed(1)}h`;
    const days = Math.floor(hours / 24);
    return `${days}d`;
  };

  return (
    <div 
      className={`bg-white border rounded-lg p-4 mb-3 transition-all ${
        isSelected ? 'border-blue-500 shadow-md' : 'border-gray-200'
      }`}
      onClick={onSelect}
    >
      {/* Header */}
      <div className="flex items-start justify-between mb-3">
        <div className="flex items-center space-x-3">
          {/* Selection Checkbox */}
          <input
            type="checkbox"
            checked={isSelected}
            onChange={onSelect}
            onClick={(e) => e.stopPropagation()}
            className="w-4 h-4 text-blue-600 rounded border-gray-300 focus:ring-blue-500"
          />
          
          {/* Symbol and Direction */}
          <div>
            <div className="flex items-center space-x-2">
              <h3 className="font-semibold text-gray-900">{trade.symbol}</h3>
              <div className="flex items-center">
                {trade.direction === 'long' ? (
                  <TrendingUp className="w-4 h-4 text-green-500" />
                ) : (
                  <TrendingDown className="w-4 h-4 text-red-500" />
                )}
                <span className={`text-xs font-medium ml-1 ${
                  trade.direction === 'long' ? 'text-green-600' : 'text-red-600'
                }`}>
                  {trade.direction.toUpperCase()}
                </span>
              </div>
            </div>
            <p className="text-xs text-gray-500 mt-0.5">{formatDate(trade.open_date)}</p>
          </div>
        </div>
        
        {/* Status Badge */}
        <div className="flex items-center space-x-2">
          <span className={`inline-flex items-center px-2 py-0.5 rounded-full text-xs font-medium ${
            trade.status === 'open' 
              ? 'bg-blue-100 text-blue-800' 
              : trade.pnl >= 0 
                ? 'bg-green-100 text-green-800'
                : 'bg-red-100 text-red-800'
          }`}>
            {trade.status === 'open' ? (
              <>
                <Clock className="w-3 h-3 mr-0.5" />
                Open
              </>
            ) : trade.pnl >= 0 ? (
              <>
                <CheckCircle className="w-3 h-3 mr-0.5" />
                Win
              </>
            ) : (
              <>
                <XCircle className="w-3 h-3 mr-0.5" />
                Loss
              </>
            )}
          </span>
          
          {/* More Actions */}
          <button
            onClick={(e) => {
              e.stopPropagation();
              // Show action menu
            }}
            className="p-1 hover:bg-gray-100 rounded"
          >
            <MoreVertical className="w-4 h-4 text-gray-500" />
          </button>
        </div>
      </div>
      
      {/* Trade Details */}
      <div className="grid grid-cols-2 gap-3">
        {/* Entry/Exit */}
        <div>
          <p className="text-xs text-gray-500">Entry → Exit</p>
          <p className="text-sm font-medium">
            ${trade.entry_price.toFixed(2)}
            {trade.exit_price && (
              <> → ${trade.exit_price.toFixed(2)}</>
            )}
          </p>
        </div>
        
        {/* Quantity */}
        <div>
          <p className="text-xs text-gray-500">Quantity</p>
          <p className="text-sm font-medium">{trade.quantity}</p>
        </div>
        
        {/* P&L */}
        <div>
          <p className="text-xs text-gray-500">P&L</p>
          <p className={`text-sm font-bold ${
            trade.pnl >= 0 ? 'text-green-600' : 'text-red-600'
          }`}>
            {formatCurrency(trade.pnl)}
            <span className="text-xs font-normal ml-1">
              ({formatPercentage(trade.pnl_percentage)})
            </span>
          </p>
        </div>
        
        {/* Duration */}
        <div>
          <p className="text-xs text-gray-500">Duration</p>
          <p className="text-sm font-medium flex items-center">
            <Clock className="w-3 h-3 mr-1 text-gray-400" />
            {formatDuration(trade.duration)}
          </p>
        </div>
      </div>
    </div>
  );
};

export default TradeMobileCard;
