// frontend/src/components/ErrorBoundary.tsx

import React, { Component, ReactNode } from 'react';

interface Props {
  children: ReactNode;
  fallback?: ReactNode;
}

interface State {
  hasError: boolean;
  error?: Error;
  errorInfo?: React.ErrorInfo;
}

export class ErrorBoundary extends Component<Props, State> {
  constructor(props: Props) {
    super(props);
    this.state = { hasError: false };
  }

  static getDerivedStateFromError(error: Error): State {
    return { hasError: true, error };
  }

  componentDidCatch(error: Error, errorInfo: React.ErrorInfo) {
    console.error('ErrorBoundary caught an error:', error, errorInfo);
    
    // Log error to external service in production
    if (process.env.NODE_ENV === 'production') {
      // TODO: Send to error reporting service
      console.error('Production Error:', {
        error: error.toString(),
        stack: error.stack,
        componentStack: errorInfo.componentStack,
        timestamp: new Date().toISOString(),
      });
    }

    this.setState({
      error,
      errorInfo,
    });
  }

  handleReload = () => {
    window.location.reload();
  };

  handleReset = () => {
    this.setState({ hasError: false, error: undefined, errorInfo: undefined });
  };

  render() {
    if (this.state.hasError) {
      if (this.props.fallback) {
        return this.props.fallback;
      }

      return (
        <div className="min-h-screen flex items-center justify-center bg-gray-50 py-12 px-4 sm:px-6 lg:px-8">
          <div className="max-w-md w-full space-y-8">
            <div className="text-center">
              <div className="mx-auto h-12 w-12 text-red-500">
                <svg fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-2.5L13.732 4c-.77-.833-1.964-.833-2.732 0L3.732 16.5c-.77.833.192 2.5 1.732 2.5z" />
                </svg>
              </div>
              <h2 className="mt-6 text-3xl font-extrabold text-gray-900">
                Oops! Something went wrong
              </h2>
              <p className="mt-2 text-sm text-gray-600">
                We're sorry for the inconvenience. The application has encountered an unexpected error.
              </p>
            </div>

            <div className="mt-8 space-y-6">
              <div className="flex flex-col space-y-3">
                <button
                  onClick={this.handleReload}
                  className="group relative w-full flex justify-center py-2 px-4 border border-transparent text-sm font-medium rounded-md text-white bg-blue-600 hover:bg-blue-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-blue-500"
                >
                  Reload Page
                </button>
                <button
                  onClick={this.handleReset}
                  className="group relative w-full flex justify-center py-2 px-4 border border-gray-300 text-sm font-medium rounded-md text-gray-700 bg-white hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-blue-500"
                >
                  Try Again
                </button>
              </div>

              {process.env.NODE_ENV === 'development' && this.state.error && (
                <details className="mt-4 p-4 bg-red-50 border border-red-200 rounded-md">
                  <summary className="text-sm font-medium text-red-800 cursor-pointer">
                    Error Details (Development Only)
                  </summary>
                  <div className="mt-2 text-xs text-red-700">
                    <p className="font-mono whitespace-pre-wrap">
                      {this.state.error.toString()}
                    </p>
                    {this.state.error.stack && (
                      <pre className="mt-2 whitespace-pre-wrap text-xs">
                        {this.state.error.stack}
                      </pre>
                    )}
                  </div>
                </details>
              )}
            </div>
          </div>
        </div>
      );
    }

    return this.props.children;
  }
}

// frontend/src/lib/components/ErrorBoundary.svelte
<script lang="ts">
	import { onMount } from 'svelte';
	import { AlertTriangle, RefreshCw, Home } from 'lucide-svelte';
	
	export let error: Error | null = null;
	export let reset: (() => void) | null = null;
	
	let errorDetails = false;
	
	onMount(() => {
		// Log error to monitoring service
		if (error) {
			console.error('Error Boundary caught:', error);
			// TODO: Send to error tracking service (Sentry, etc.)
		}
	});
	
	function handleReset() {
		if (reset) {
			reset();
		} else {
			location.reload();
		}
	}
</script>

<div class="min-h-[400px] flex items-center justify-center p-4">
	<div class="max-w-md w-full bg-white dark:bg-gray-800 rounded-lg shadow-lg p-6">
		<div class="flex items-center justify-center mb-4">
			<div class="bg-red-100 dark:bg-red-900/20 rounded-full p-3">
				<AlertTriangle class="h-8 w-8 text-red-600 dark:text-red-400" />
			</div>
		</div>
		
		<h2 class="text-xl font-semibold text-gray-900 dark:text-white text-center mb-2">
			Something went wrong
		</h2>
		
		<p class="text-gray-600 dark:text-gray-400 text-center mb-6">
			We encountered an unexpected error. Please try refreshing the page.
		</p>
		
		{#if error && errorDetails}
			<div class="mb-6 p-3 bg-gray-100 dark:bg-gray-900 rounded border border-gray-200 dark:border-gray-700">
				<p class="text-sm font-mono text-gray-700 dark:text-gray-300 break-all">
					{error.message}
				</p>
				{#if error.stack}
					<details class="mt-2">
						<summary class="text-xs text-gray-500 cursor-pointer hover:text-gray-700 dark:hover:text-gray-300">
							Stack trace
						</summary>
						<pre class="mt-2 text-xs text-gray-600 dark:text-gray-400 overflow-x-auto">{error.stack}</pre>
					</details>
				{/if}
			</div>
		{/if}
		
		<div class="flex flex-col sm:flex-row gap-3">
			<button
				on:click={handleReset}
				class="flex-1 flex items-center justify-center gap-2 px-4 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700 transition-colors"
			>
				<RefreshCw class="h-4 w-4" />
				Try Again
			</button>
			
			<a
				href="/"
				class="flex-1 flex items-center justify-center gap-2 px-4 py-2 bg-gray-200 dark:bg-gray-700 text-gray-700 dark:text-gray-300 rounded-lg hover:bg-gray-300 dark:hover:bg-gray-600 transition-colors"
			>
				<Home class="h-4 w-4" />
				Go Home
			</a>
		</div>
		
		{#if error && !errorDetails}
			<button
				on:click={() => errorDetails = true}
				class="mt-4 text-xs text-gray-500 hover:text-gray-700 dark:hover:text-gray-300 underline w-full text-center"
			>
				Show error details
			</button>
		{/if}
	</div>
</div>
